mock_events = [
    {
        "id": 26,
        "title": "Ninajirachi - Live in Melbourne",
        "slug": "ninajirachi-live-melbourne",
        "event_date": "2026-07-16",
        "event_time": "20:00",
        "event_type": "concert",
        "genre": "electronic",
        "city": "Melbourne",
        "venue": "Forum Melbourne",
        "artist": "Ninajirachi",
        "lineup": ["Ninajirachi"],
        "image_url": "https://images.unsplash.com/photo-1501386761578-eac5c94b800a",
        "status": "upcoming",
        "ticket_links": [
            {
                "provider": "Ticketek",
                "url": "https://premier.ticketek.com.au/",
                "is_primary": True,
            }
        ],
    },
    {
        "id": 27,
        "title": "Laneway Festival Melbourne",
        "slug": "laneway-festival-melbourne",
        "event_date": "2026-02-08",
        "event_time": "12:00",
        "event_type": "festival",
        "genre": "pop",
        "city": "Melbourne",
        "venue": "Flemington Park",
        "artist": "Laneway Festival",
        "lineup": ["Artist A", "Artist B", "Artist C"],
        "image_url": "https://images.unsplash.com/photo-1459749411175-04bf5292ceea",
        "status": "upcoming",
        "ticket_links": [
            {
                "provider": "Official Website",
                "url": "https://www.lanewayfestival.com/",
                "is_primary": True,
            }
        ],
    },    {
        "id": "1",
        "title": "Melbourne Indie Night",
        "slug": "melbourne-indie-night",
        "event_date": "2026-06-15",
        "event_time": "19:30",
        "event_type": "concert",
        "city": "Melbourne",
        "venue": "The Forum",
        "artist": "The Southern Lights",
        "lineup": ["The Southern Lights", "Velvet Coast"],
        "genre": "indie",
        "image_url": "https://images.unsplash.com/photo-1501386761578-eac5c94b800a",
        "youtube_embed_url": "https://www.youtube.com/embed/VIDEO_ID_HERE",
        "status": "upcoming",
        "ticket_links": [
            {
                "provider": "Ticketmaster",
                "url": "https://www.ticketmaster.com.au",
                "is_primary": True,
            }
        ],
        "source_url": "https://www.ticketmaster.com.au",
    },
    {
        "id": "2",
        "title": "Sydney Rock Festival",
        "slug": "sydney-rock-festival",
        "event_date": "2026-07-02",
        "event_time": "18:00",
        "event_type": "festival",
        "city": "Sydney",
        "venue": "Hordern Pavilion",
        "artist": "Harbour Static",
        "lineup": ["Harbour Static", "Northline", "Echo Parade"],
        "genre": "rock",
        "image_url": "https://images.unsplash.com/photo-1493225457124-a3eb161ffa5f",
        "status": "upcoming",
        "ticket_links": [
            {
                "provider": "Ticketek",
                "url": "https://premier.ticketek.com.au",
                "is_primary": True,
            }
        ],
        "source_url": "https://premier.ticketek.com.au",
    },
    {
        "id": "3",
        "title": "Brisbane DJ Set: Midnight Circuit",
        "slug": "brisbane-dj-set-midnight-circuit",
        "event_date": "2026-06-28",
        "event_time": "22:00",
        "event_type": "dj-set",
        "city": "Brisbane",
        "venue": "The Tivoli",
        "artist": "Midnight Circuit",
        "lineup": ["Midnight Circuit", "DJ Nova"],
        "genre": "electronic",
        "image_url": "https://images.unsplash.com/photo-1571266028243-d220c6a7edbf",
        "status": "upcoming",
        "ticket_links": [
            {
                "provider": "Moshtix",
                "url": "https://www.moshtix.com.au",
                "is_primary": True,
            }
        ],
        "source_url": "https://www.moshtix.com.au",
    },
    {
        "id": "4",
        "title": "Perth Summer Beats",
        "slug": "perth-summer-beats",
        "event_date": "2026-08-10",
        "event_time": "20:00",
        "event_type": "party-night",
        "city": "Perth",
        "venue": "Metro City",
        "artist": "Coastal Rhythm",
        "lineup": ["Coastal Rhythm", "Late Drive"],
        "genre": "pop",
        "image_url": "https://images.unsplash.com/photo-1514525253161-7a46d19cd819",
        "status": "upcoming",
        "ticket_links": [
            {
                "provider": "Eventbrite",
                "url": "https://www.eventbrite.com.au",
                "is_primary": True,
            }
        ],
        "source_url": "https://www.eventbrite.com.au",
    },
    {
        "id": "5",
        "title": "Adelaide Acoustic Sessions",
        "slug": "adelaide-acoustic-sessions",
        "event_date": "2026-06-20",
        "event_time": "19:00",
        "event_type": "concert",
        "city": "Adelaide",
        "venue": "The Gov",
        "artist": "Maya Hart",
        "lineup": ["Maya Hart", "James River"],
        "genre": "acoustic",
        "image_url": "https://images.unsplash.com/photo-1516280440614-37939bbacd81",
        "status": "upcoming",
        "ticket_links": [
            {
                "provider": "Ticketmaster",
                "url": "https://www.ticketmaster.com.au",
                "is_primary": True,
            }
        ],
        "source_url": "https://www.ticketmaster.com.au",
    },
    {
        "id": "6",
        "title": "Melbourne Jazz After Dark",
        "slug": "melbourne-jazz-after-dark",
        "event_date": "2026-07-12",
        "event_time": "20:30",
        "event_type": "concert",
        "city": "Melbourne",
        "venue": "Bird's Basement",
        "artist": "Blue Lane Quartet",
        "lineup": ["Blue Lane Quartet", "Sophie Miles"],
        "genre": "jazz",
        "image_url": "https://images.unsplash.com/photo-1415201364774-f6f0bb35f28f",
        "status": "upcoming",
        "ticket_links": [
            {
                "provider": "Eventbrite",
                "url": "https://www.eventbrite.com.au",
                "is_primary": True,
            }
        ],
        "source_url": "https://www.eventbrite.com.au",
    },
    {
        "id": "7",
        "title": "Sydney Pop Night",
        "slug": "sydney-pop-night",
        "event_date": "2026-06-18",
        "event_time": "19:45",
        "event_type": "concert",
        "city": "Sydney",
        "venue": "Enmore Theatre",
        "artist": "Luna Bay",
        "lineup": ["Luna Bay", "Glass Avenue"],
        "genre": "pop",
        "image_url": "https://images.unsplash.com/photo-1506157786151-b8491531f063",
        "status": "upcoming",
        "ticket_links": [
            {
                "provider": "Ticketek",
                "url": "https://premier.ticketek.com.au",
                "is_primary": True,
            }
        ],
        "source_url": "https://premier.ticketek.com.au",
    },
    {
        "id": "8",
        "title": "Brisbane River Festival",
        "slug": "brisbane-river-festival",
        "event_date": "2026-09-05",
        "event_time": "15:00",
        "event_type": "festival",
        "city": "Brisbane",
        "venue": "Riverstage",
        "artist": "Various Artists",
        "lineup": ["Sunset Arcade", "The Valley Kids", "DJ Kora"],
        "genre": "mixed",
        "image_url": "https://images.unsplash.com/photo-1470229722913-7c0e2dbbafd3",
        "status": "upcoming",
        "ticket_links": [
            {
                "provider": "Moshtix",
                "url": "https://www.moshtix.com.au",
                "is_primary": True,
            }
        ],
        "source_url": "https://www.moshtix.com.au",
    },
    {
        "id": "9",
        "title": "Perth Electronic Underground",
        "slug": "perth-electronic-underground",
        "event_date": "2026-07-25",
        "event_time": "23:00",
        "event_type": "dj-set",
        "city": "Perth",
        "venue": "Jack Rabbit Slim's",
        "artist": "Neon Harbour",
        "lineup": ["Neon Harbour", "DJ Pulse", "Static Bloom"],
        "genre": "electronic",
        "image_url": "https://images.unsplash.com/photo-1507874457470-272b3c8d8ee2",
        "status": "upcoming",
        "ticket_links": [
            {
                "provider": "Eventbrite",
                "url": "https://www.eventbrite.com.au",
                "is_primary": True,
            }
        ],
        "source_url": "https://www.eventbrite.com.au",
    },
    {
        "id": "10",
        "title": "Adelaide Folk Evening",
        "slug": "adelaide-folk-evening",
        "event_date": "2026-08-14",
        "event_time": "18:30",
        "event_type": "concert",
        "city": "Adelaide",
        "venue": "Jive",
        "artist": "Clara Stone",
        "lineup": ["Clara Stone", "The Old Tracks"],
        "genre": "folk",
        "image_url": "https://images.unsplash.com/photo-1499364615650-ec38552f4f34",
        "status": "upcoming",
        "ticket_links": [
            {
                "provider": "Ticketmaster",
                "url": "https://www.ticketmaster.com.au",
                "is_primary": True,
            }
        ],
        "source_url": "https://www.ticketmaster.com.au",
    },
    {
        "id": "11",
        "title": "Melbourne Warehouse Party",
        "slug": "melbourne-warehouse-party",
        "event_date": "2026-06-30",
        "event_time": "22:30",
        "event_type": "party-night",
        "city": "Melbourne",
        "venue": "170 Russell",
        "artist": "Night Signal",
        "lineup": ["Night Signal", "DJ Luma", "East End Crew"],
        "genre": "house",
        "image_url": "https://images.unsplash.com/photo-1492684223066-81342ee5ff30",
        "status": "upcoming",
        "ticket_links": [
            {
                "provider": "Moshtix",
                "url": "https://www.moshtix.com.au",
                "is_primary": True,
            }
        ],
        "source_url": "https://www.moshtix.com.au",
    },
    {
        "id": "12",
        "title": "Sydney Hip Hop Showcase",
        "slug": "sydney-hip-hop-showcase",
        "event_date": "2026-07-19",
        "event_time": "20:00",
        "event_type": "concert",
        "city": "Sydney",
        "venue": "Metro Theatre",
        "artist": "Westside Motion",
        "lineup": ["Westside Motion", "Kay Nine", "Mira Flow"],
        "genre": "hip-hop",
        "image_url": "https://images.unsplash.com/photo-1521337581100-8ca9a73a5f79",
        "status": "upcoming",
        "ticket_links": [
            {
                "provider": "Ticketek",
                "url": "https://premier.ticketek.com.au",
                "is_primary": True,
            }
        ],
        "source_url": "https://premier.ticketek.com.au",
    },
    {
        "id": "13",
        "title": "Brisbane Indie Pop Club",
        "slug": "brisbane-indie-pop-club",
        "event_date": "2026-08-03",
        "event_time": "19:30",
        "event_type": "party-night",
        "city": "Brisbane",
        "venue": "The Zoo",
        "artist": "Peach Motel",
        "lineup": ["Peach Motel", "Small Talk"],
        "genre": "indie pop",
        "image_url": "https://images.unsplash.com/photo-1516450360452-9312f5e86fc7",
        "status": "upcoming",
        "ticket_links": [
            {
                "provider": "Eventbrite",
                "url": "https://www.eventbrite.com.au",
                "is_primary": True,
            }
        ],
        "source_url": "https://www.eventbrite.com.au",
    },
    {
        "id": "14",
        "title": "Melbourne Classical Live",
        "slug": "melbourne-classical-live",
        "event_date": "2026-09-18",
        "event_time": "19:00",
        "event_type": "concert",
        "city": "Melbourne",
        "venue": "Hamer Hall",
        "artist": "Melbourne Chamber Players",
        "lineup": ["Melbourne Chamber Players"],
        "genre": "classical",
        "image_url": "https://images.unsplash.com/photo-1465847899084-d164df4dedc6",
        "status": "upcoming",
        "ticket_links": [
            {
                "provider": "Ticketmaster",
                "url": "https://www.ticketmaster.com.au",
                "is_primary": True,
            }
        ],
        "source_url": "https://www.ticketmaster.com.au",
    },
    {
        "id": "15",
        "title": "Perth Rock Revival",
        "slug": "perth-rock-revival",
        "event_date": "2026-06-22",
        "event_time": "20:15",
        "event_type": "concert",
        "city": "Perth",
        "venue": "The Rechabite",
        "artist": "Red Desert Road",
        "lineup": ["Red Desert Road", "Stone Avenue"],
        "genre": "rock",
        "image_url": "https://images.unsplash.com/photo-1505236858219-8359eb29e329",
        "status": "upcoming",
        "ticket_links": [
            {
                "provider": "Moshtix",
                "url": "https://www.moshtix.com.au",
                "is_primary": True,
            }
        ],
        "source_url": "https://www.moshtix.com.au",
    },
    {
        "id": "16",
        "title": "Adelaide Dance Hall",
        "slug": "adelaide-dance-hall",
        "event_date": "2026-07-08",
        "event_time": "21:00",
        "event_type": "dj-set",
        "city": "Adelaide",
        "venue": "Lion Arts Factory",
        "artist": "DJ Solace",
        "lineup": ["DJ Solace", "Tempo Lane"],
        "genre": "dance",
        "image_url": "https://images.unsplash.com/photo-1519671482749-fd09be7ccebf",
        "status": "upcoming",
        "ticket_links": [
            {
                "provider": "Eventbrite",
                "url": "https://www.eventbrite.com.au",
                "is_primary": True,
            }
        ],
        "source_url": "https://www.eventbrite.com.au",
    },
    {
        "id": "17",
        "title": "Sydney Latin Night",
        "slug": "sydney-latin-night",
        "event_date": "2026-08-22",
        "event_time": "20:30",
        "event_type": "party-night",
        "city": "Sydney",
        "venue": "Oxford Art Factory",
        "artist": "Casa Luna",
        "lineup": ["Casa Luna", "DJ Rio"],
        "genre": "latin",
        "image_url": "https://images.unsplash.com/photo-1533174072545-7a4b6ad7a6c3",
        "status": "upcoming",
        "ticket_links": [
            {
                "provider": "Ticketek",
                "url": "https://premier.ticketek.com.au",
                "is_primary": True,
            }
        ],
        "source_url": "https://premier.ticketek.com.au",
    },
    {
        "id": "18",
        "title": "Melbourne Punk Basement",
        "slug": "melbourne-punk-basement",
        "event_date": "2026-07-29",
        "event_time": "21:00",
        "event_type": "concert",
        "city": "Melbourne",
        "venue": "The Tote",
        "artist": "Broken Signal",
        "lineup": ["Broken Signal", "Cold Vinyl"],
        "genre": "punk",
        "image_url": "https://images.unsplash.com/photo-1598387993441-a364f854c3e1",
        "status": "upcoming",
        "ticket_links": [
            {
                "provider": "Moshtix",
                "url": "https://www.moshtix.com.au",
                "is_primary": True,
            }
        ],
        "source_url": "https://www.moshtix.com.au",
    },
    {
        "id": "19",
        "title": "Brisbane Country Live",
        "slug": "brisbane-country-live",
        "event_date": "2026-09-11",
        "event_time": "18:00",
        "event_type": "concert",
        "city": "Brisbane",
        "venue": "Fortitude Music Hall",
        "artist": "Riverbend County",
        "lineup": ["Riverbend County", "Ella North"],
        "genre": "country",
        "image_url": "https://images.unsplash.com/photo-1516280440614-37939bbacd81",
        "status": "upcoming",
        "ticket_links": [
            {
                "provider": "Ticketmaster",
                "url": "https://www.ticketmaster.com.au",
                "is_primary": True,
            }
        ],
        "source_url": "https://www.ticketmaster.com.au",
    },
    {
        "id": "20",
        "title": "Perth Festival of Sound",
        "slug": "perth-festival-of-sound",
        "event_date": "2026-10-04",
        "event_time": "14:00",
        "event_type": "festival",
        "city": "Perth",
        "venue": "Langley Park",
        "artist": "Various Artists",
        "lineup": ["Skyline Drive", "Neon Harbour", "Maya Hart", "DJ Solace"],
        "genre": "mixed",
        "image_url": "https://images.unsplash.com/photo-1459749411175-04bf5292ceea",
        "status": "upcoming",
        "ticket_links": [
            {
                "provider": "Eventbrite",
                "url": "https://www.eventbrite.com.au",
                "is_primary": True,
            }
        ],
        "source_url": "https://www.eventbrite.com.au",
    },
    {
        "id": "21",
        "title": "Melbourne Winter Beats",
        "slug": "melbourne-winter-beats",
        "event_date": "2026-05-05",
        "event_time": "20:00",
        "event_type": "dj-set",
        "city": "Melbourne",
        "venue": "Sub Club",
        "artist": "Arctic Loop",
        "lineup": ["Arctic Loop", "DJ Vale"],
        "genre": "techno",
        "image_url": "https://images.unsplash.com/photo-1571266028243-d220c6a7edbf",
        "status": "past",
        "ticket_links": [
            {
                "provider": "Moshtix",
                "url": "https://www.moshtix.com.au",
                "is_primary": True,
            }
        ],
        "source_url": "https://www.moshtix.com.au",
    },
    {
        "id": "22",
        "title": "Sydney Autumn Sessions",
        "slug": "sydney-autumn-sessions",
        "event_date": "2026-04-16",
        "event_time": "19:00",
        "event_type": "concert",
        "city": "Sydney",
        "venue": "Manning Bar",
        "artist": "Soft Arcade",
        "lineup": ["Soft Arcade", "Blue Paper"],
        "genre": "indie",
        "image_url": "https://images.unsplash.com/photo-1516280440614-37939bbacd81",
        "status": "past",
        "ticket_links": [
            {
                "provider": "Ticketek",
                "url": "https://premier.ticketek.com.au",
                "is_primary": True,
            }
        ],
        "source_url": "https://premier.ticketek.com.au",
    },
    {
        "id": "23",
        "title": "Brisbane Night Market Sounds",
        "slug": "brisbane-night-market-sounds",
        "event_date": "2026-05-18",
        "event_time": "18:30",
        "event_type": "festival",
        "city": "Brisbane",
        "venue": "South Bank Piazza",
        "artist": "Various Artists",
        "lineup": ["River Kids", "Mira Flow", "DJ Kora"],
        "genre": "mixed",
        "image_url": "https://images.unsplash.com/photo-1501386761578-eac5c94b800a",
        "status": "past",
        "ticket_links": [
            {
                "provider": "Eventbrite",
                "url": "https://www.eventbrite.com.au",
                "is_primary": True,
            }
        ],
        "source_url": "https://www.eventbrite.com.au",
    },
    {
        "id": "24",
        "title": "Adelaide Garage Rock Night",
        "slug": "adelaide-garage-rock-night",
        "event_date": "2026-05-27",
        "event_time": "21:00",
        "event_type": "concert",
        "city": "Adelaide",
        "venue": "Crown and Anchor",
        "artist": "Static Garage",
        "lineup": ["Static Garage", "The Rearview"],
        "genre": "garage rock",
        "image_url": "https://images.unsplash.com/photo-1493225457124-a3eb161ffa5f",
        "status": "past",
        "ticket_links": [
            {
                "provider": "Moshtix",
                "url": "https://www.moshtix.com.au",
                "is_primary": True,
            }
        ],
        "source_url": "https://www.moshtix.com.au",
    },
    {
        "id": "25",
        "title": "Perth Sunset Party",
        "slug": "perth-sunset-party",
        "event_date": "2026-05-30",
        "event_time": "17:30",
        "event_type": "party-night",
        "city": "Perth",
        "venue": "Scarborough Beach Amphitheatre",
        "artist": "Golden Hour Club",
        "lineup": ["Golden Hour Club", "DJ Coastline"],
        "genre": "dance pop",
        "image_url": "https://images.unsplash.com/photo-1514525253161-7a46d19cd819",
        "status": "past",
        "ticket_links": [
            {
                "provider": "Eventbrite",
                "url": "https://www.eventbrite.com.au",
                "is_primary": True,
            }
        ],
        "source_url": "https://www.eventbrite.com.au",
    },
]