mock_events = [
    {
        "id": 1,
        "title": "Ninajirachi - Live in Melbourne",
        "slug": "ninajirachi-live-melbourne",
        "event_date": "2026-07-12",
        "event_time": "20:00",
        "event_type": "concert",
        "genre": "electronic",
        "city": "Melbourne",
        "state": "VIC",
        "venue": {
            "id": 1,
            "name": "Forum Melbourne",
            "slug": "forum-melbourne",
            "city": "Melbourne",
            "state": "VIC",
            "address": "154 Flinders St, Melbourne VIC",
            "image_url": "https://images.unsplash.com/photo-1492684223066-81342ee5ff30",
        },
        "artist": {
            "id": 1,
            "name": "Ninajirachi",
            "slug": "ninajirachi",
            "image_url": "https://images.unsplash.com/photo-1516280440614-37939bbacd81",
            "genre": "electronic",
        },
        "lineup": [
            {
                "id": 1,
                "name": "Ninajirachi",
                "slug": "ninajirachi",
                "image_url": "https://images.unsplash.com/photo-1516280440614-37939bbacd81",
                "genre": "electronic",
            }
        ],
        "image_url": "https://images.unsplash.com/photo-1501386761578-eac5c94b800a",
        "youtube_embed_url": "https://www.youtube.com/embed/dQw4w9WgXcQ",
        "status": "upcoming",
        "ticket_links": [
            {
                "provider": "Ticketmaster",
                "url": "https://www.ticketmaster.com.au/",
                "is_primary": True,
            },
            {
                "provider": "Tixel",
                "url": "https://tixel.com/au",
                "is_primary": False,
            },
        ],
    },
    {
        "id": 2,
        "title": "Laneway Festival Melbourne",
        "slug": "laneway-festival-melbourne",
        "event_date": "2026-08-03",
        "event_time": "12:00",
        "event_type": "festival",
        "genre": "indie",
        "city": "Melbourne",
        "state": "VIC",
        "venue": {
            "id": 2,
            "name": "Flemington Racecourse",
            "slug": "flemington-racecourse",
            "city": "Melbourne",
            "state": "VIC",
            "address": "448 Epsom Rd, Flemington VIC",
            "image_url": "https://images.unsplash.com/photo-1470229722913-7c0e2dbbafd3",
        },
        "artist": {
            "id": 2,
            "name": "Laneway Festival",
            "slug": "laneway-festival",
            "image_url": "https://images.unsplash.com/photo-1506157786151-b8491531f063",
            "genre": "indie",
        },
        "lineup": [
            {
                "id": 3,
                "name": "Men I Trust",
                "slug": "men-i-trust",
                "image_url": "https://images.unsplash.com/photo-1521337581100-8ca9a73a5f79",
                "genre": "indie",
            },
            {
                "id": 4,
                "name": "Clairo",
                "slug": "clairo",
                "image_url": "https://images.unsplash.com/photo-1494790108377-be9c29b29330",
                "genre": "indie",
            },
            {
                "id": 5,
                "name": "The Beths",
                "slug": "the-beths",
                "image_url": "https://images.unsplash.com/photo-1516280440614-37939bbacd81",
                "genre": "alternative",
            },
        ],
        "image_url": "https://images.unsplash.com/photo-1459749411175-04bf5292ceea",
        "youtube_embed_url": None,
        "status": "upcoming",
        "ticket_links": [
            {
                "provider": "Moshtix",
                "url": "https://www.moshtix.com.au/",
                "is_primary": True,
            },
            {
                "provider": "Ticketek",
                "url": "https://premier.ticketek.com.au/",
                "is_primary": False,
            },
        ],
    },
    {
        "id": 3,
        "title": "Boiler Room Sydney",
        "slug": "boiler-room-sydney",
        "event_date": "2026-07-26",
        "event_time": "22:00",
        "event_type": "dj-set",
        "genre": "dance",
        "city": "Sydney",
        "state": "NSW",
        "venue": {
            "id": 3,
            "name": "Hordern Pavilion",
            "slug": "hordern-pavilion",
            "city": "Sydney",
            "state": "NSW",
            "address": "1 Driver Ave, Moore Park NSW",
            "image_url": "https://images.unsplash.com/photo-1507874457470-272b3c8d8ee2",
        },
        "artist": {
            "id": 6,
            "name": "Boiler Room",
            "slug": "boiler-room",
            "image_url": "https://images.unsplash.com/photo-1571266028243-d220c9c3b9be",
            "genre": "dance",
        },
        "lineup": [
            {
                "id": 7,
                "name": "Mall Grab",
                "slug": "mall-grab",
                "image_url": "https://images.unsplash.com/photo-1500530855697-b586d89ba3ee",
                "genre": "dance",
            },
            {
                "id": 8,
                "name": "CC:DISCO!",
                "slug": "cc-disco",
                "image_url": "https://images.unsplash.com/photo-1514525253161-7a46d19cd819",
                "genre": "dance",
            },
        ],
        "image_url": "https://images.unsplash.com/photo-1506157786151-b8491531f063",
        "youtube_embed_url": None,
        "status": "upcoming",
        "ticket_links": [
            {
                "provider": "Eventbrite",
                "url": "https://www.eventbrite.com.au/",
                "is_primary": True,
            }
        ],
    },
    {
        "id": 4,
        "title": "RÜFÜS DU SOL - Sydney",
        "slug": "rufus-du-sol-sydney",
        "event_date": "2026-09-14",
        "event_time": "19:30",
        "event_type": "concert",
        "genre": "electronic",
        "city": "Sydney",
        "state": "NSW",
        "venue": {
            "id": 4,
            "name": "Qudos Bank Arena",
            "slug": "qudos-bank-arena",
            "city": "Sydney",
            "state": "NSW",
            "address": "Olympic Blvd, Sydney Olympic Park NSW",
            "image_url": "https://images.unsplash.com/photo-1540039155733-5bb30b53aa14",
        },
        "artist": {
            "id": 9,
            "name": "RÜFÜS DU SOL",
            "slug": "rufus-du-sol",
            "image_url": "https://images.unsplash.com/photo-1500530855697-b586d89ba3ee",
            "genre": "electronic",
        },
        "lineup": [
            {
                "id": 9,
                "name": "RÜFÜS DU SOL",
                "slug": "rufus-du-sol",
                "image_url": "https://images.unsplash.com/photo-1500530855697-b586d89ba3ee",
                "genre": "electronic",
            }
        ],
        "image_url": "https://images.unsplash.com/photo-1429962714451-bb934ecdc4ec",
        "youtube_embed_url": "https://www.youtube.com/embed/dQw4w9WgXcQ",
        "status": "upcoming",
        "ticket_links": [
            {
                "provider": "Ticketek",
                "url": "https://premier.ticketek.com.au/",
                "is_primary": True,
            }
        ],
    },
    {
        "id": 5,
        "title": "Perth Hip-Hop Night",
        "slug": "perth-hip-hop-night",
        "event_date": "2026-06-22",
        "event_time": "21:00",
        "event_type": "party-night",
        "genre": "hip-hop",
        "city": "Perth",
        "state": "WA",
        "venue": {
            "id": 5,
            "name": "The Rechabite",
            "slug": "the-rechabite",
            "city": "Perth",
            "state": "WA",
            "address": "224 William St, Northbridge WA",
            "image_url": "https://images.unsplash.com/photo-1492447166138-50c3889fccb1",
        },
        "artist": {
            "id": 10,
            "name": "Perth Hip-Hop Collective",
            "slug": "perth-hip-hop-collective",
            "image_url": "https://images.unsplash.com/photo-1516280440614-37939bbacd81",
            "genre": "hip-hop",
        },
        "lineup": [
            {
                "id": 10,
                "name": "Perth Hip-Hop Collective",
                "slug": "perth-hip-hop-collective",
                "image_url": "https://images.unsplash.com/photo-1516280440614-37939bbacd81",
                "genre": "hip-hop",
            }
        ],
        "image_url": "https://images.unsplash.com/photo-1493225457124-a3eb161ffa5f",
        "youtube_embed_url": None,
        "status": "upcoming",
        "ticket_links": [
            {
                "provider": "Eventbrite",
                "url": "https://www.eventbrite.com.au/",
                "is_primary": True,
            }
        ],
    },
    {
        "id": 6,
        "title": "Clairo - Brisbane",
        "slug": "clairo-brisbane",
        "event_date": "2025-11-18",
        "event_time": "19:00",
        "event_type": "concert",
        "genre": "indie",
        "city": "Brisbane",
        "state": "QLD",
        "venue": {
            "id": 6,
            "name": "Fortitude Music Hall",
            "slug": "fortitude-music-hall",
            "city": "Brisbane",
            "state": "QLD",
            "address": "312-318 Brunswick St, Fortitude Valley QLD",
            "image_url": "https://images.unsplash.com/photo-1516450360452-9312f5e86fc7",
        },
        "artist": {
            "id": 4,
            "name": "Clairo",
            "slug": "clairo",
            "image_url": "https://images.unsplash.com/photo-1494790108377-be9c29b29330",
            "genre": "indie",
        },
        "lineup": [
            {
                "id": 4,
                "name": "Clairo",
                "slug": "clairo",
                "image_url": "https://images.unsplash.com/photo-1494790108377-be9c29b29330",
                "genre": "indie",
            }
        ],
        "image_url": "https://images.unsplash.com/photo-1524368535928-5b5e00ddc76b",
        "youtube_embed_url": None,
        "status": "past",
        "ticket_links": [
            {
                "provider": "Ticketmaster",
                "url": "https://www.ticketmaster.com.au/",
                "is_primary": True,
            }
        ],
    },
]
